AllCops:
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'vendor/**/*'
    - 'lib/tasks/cucumber.rake'
  TargetRubyVersion: 2.4

Documentation:
  Enabled: false

Lint/HandleExceptions:
  Exclude:
    - Rakefile

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'features/step_definitions/*.rb'

Metrics/ClassLength:
  Exclude:
    - 'app/models/statement_stats.rb'

Rails:
  Enabled: true

Rails/HasAndBelongsToMany:
  Exclude:
    - 'app/models/company.rb'
    - 'app/models/statement.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'config/routes.rb'
    - 'config/sitemap.rb'
    - 'config/environments/*.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/AsciiComments:
  Enabled: false
