version: 0.0
os: linux
files:
  - source: /config.ru
    destination: /home/ec2-user/ruby-on-rails
  - source: /Gemfile
    destination: /home/ec2-user/ruby-on-rails
  - source: /Gemfile.lock
    destination: /home/ec2-user/ruby-on-rails
  - source: /Rakefile
    destination: /home/ec2-user/ruby-on-rails
  - source: /app/
    destination: /home/ec2-user/ruby-on-rails/app
  - source: /config/
    destination: /home/ec2-user/ruby-on-rails/config
  - source: /db/
    destination: /home/ec2-user/ruby-on-rails/db
  - source: /deploy/
    destination: /home/ec2-user/ruby-on-rails/deploy
  - source: /features/
    destination: /home/ec2-user/ruby-on-rails/features
  - source: /lib/
    destination: /home/ec2-user/ruby-on-rails/lib
  - source: /log/
    destination: /home/ec2-user/ruby-on-rails/log
  - source: /vendor/
    destination: /home/ec2-user/ruby-on-rails/vendor
  - source: /Procfile
    destination: /home/ec2-user/ruby-on-rails
  - source: /public/
    destination: /home/ec2-user/ruby-on-rails/public
  - source: /spec/
    destination: /home/ec2-user/ruby-on-rails/spec

hooks:
  AfterInstall:
    - location: deploy/install_dependencies
      timeout: 1800
      runas: root
  ApplicationStart:
    - location: deploy/start_server
      timeout: 300
      runas: ec2-user 
  ApplicationStop:
    - location: deploy/stop_server
      timeout: 300
      runas: ec2-user 
