#!/bin/bash

add-apt-repository -y ppa:brightbox/ruby-ng

add-apt-repository -y "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -sc)-pgdg main"
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -

apt-get update

apt-get install -y imagemagick

apt-get install -y ruby2.4 ruby2.4-dev

gem update --system
gem install bundler
gem install foreman

apt-get install -y libxrender1
apt-get install -y libfontconfig1
apt-get install -y libxext6
apt-get install -y build-essential zlib1g-dev libxml2-dev

update-locale LANG=en_US.UTF-8

apt-get install -y postgresql-client-9.6
apt-get install -y libpqxx-dev

apt-get install -y redis-server

apt-get install -y nodejs

apt-get install -y python-pip
pip install awscli

if [ ! -f /usr/local/bin/wkhtmltoimage ]; then
	cd /tmp
	wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
	unxz wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
	tar -xvf wkhtmltox-0.12.4_linux-generic-amd64.tar
	mv wkhtmltox/bin/* /usr/local/bin/
	rm -rf /tmp/wkhtmltox
	rm -f /tmp/wkhtmltox-0.12.4_linux-generic-amd64.tar
fi

chown -R ubuntu:ubuntu /home/ubuntu/ruby-on-rails

service redis start
