#!/bin/bash
function secret_key () {
  password=$( aws ssm get-parameters --region eu-west-1 --names $1 --with-decryption --query Parameters[0].Value )
  password=`echo $password | sed -e 's/^"//' -e 's/"$//'`
  echo $password
}

cd /home/ubuntu/ruby-on-rails

cat <<EOF > .env
RAILS_ENV=production

LANG=en_US.UTF-8
PORT=3000

RAILS_LOG_TO_STDOUT=enabled
RAILS_SERVE_STATIC_FILES=enabled
ROLLBAR_ENDPOINT=https://api.rollbar.com/api/1/item/
SEED_ADMIN_EMAIL=carrier@business-humanrights.org

DATABASE_URL=$( secret_key ms-db-url )
SECRET_KEY_BASE=$( secret_key ms-secret-key )
SENDGRID_USERNAME=$( secret_key ms-sendgrid-user )
SENDGRID_PASSWORD=$( secret_key ms-sendgrid-password )
ROLLBAR_ACCESS_TOKEN=$( secret_key ms-rollbar-access-token )

AWS_ACCESS_KEY_ID=$( secret_key ms-aws-access-key-id )
AWS_SECRET_ACCESS_KEY=$( secret_key ms-aws-secret-access-key )

EOF

set -a # automatically export all variables
source .env
set +a
export PATH=$PATH:/usr/local/bin

bundle install --deployment
bundle exec rake assets:precompile
bundle exec rake db:migrate

sudo foreman  export -e .env -a railsapp -u ubuntu -d /home/ubuntu/ruby-on-rails systemd /etc/systemd/system

sudo systemctl start railsapp.target
