#!/usr/bin/env ruby
#
# This script imports Countries from http://www.geonames.org/ into the database
#
# Usage:
#    GEONAMES_USERNAME=XXX ./bin/rails runner script/import-countries
# Heroku:
#    heroku config:set GEONAMES_USERNAME=XXX --app=msa-registry
#    heroku run --app=msa-registry rails runner script/import-countries
#
require 'json'
require 'geonames'

geonames_username = ENV['GEONAMES_USERNAME']
if geonames_username.nil?
  puts "You need to define GEONAMES_USERNAME"
  puts "sign up for an account and activate the web service"
  puts
  exit 1
end

puts "There are #{Country.count} countries in the database. Importing..."
res = Geonames::WebService.make_request("/countryInfoJSON?username=#{geonames_username}&a=a&")
body = JSON.parse(res.body)
body['geonames'].each do |country_info|
  lat = (country_info['north'].to_f + country_info['south'].to_f)/2
  lng = (country_info['west'].to_f + country_info['east'].to_f)/2

  begin
    Country.find_or_create_by!({
      code: country_info['countryCode'],
      name: country_info['countryName'],
      lat: lat,
      lng: lng
    })
  rescue ActiveRecord::RecordNotUnique
    Country.where({
      code: country_info['countryCode'],
      name: country_info['countryName']
    }).update_all({
      lat: lat,
      lng: lng
    })
  end
end
puts "There are #{Country.count} countries in the database."
